# Generated by Django 4.2.4 on 2023-08-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkboxes',
            name='links',
        ),
        migrations.AddField(
            model_name='links',
            name='box',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='site_module.linkboxes'),
            preserve_default=False,
        ),
    ]
