# Generated by Django 4.2.4 on 2023-08-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0012_articlecomments_is_view_by_admin'),
        ('site_module', '0002_remove_linkboxes_links_links_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article')),
            ],
        ),
    ]
