# Generated by Django 4.2.4 on 2023-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_view_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
