# Generated by Django 4.2.4 on 2023-08-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_update',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
