# Generated by Django 4.2.4 on 2023-08-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article_is_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
