# Generated by Django 4.2.4 on 2023-08-11 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_article_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
