# Generated by Django 4.2.4 on 2023-08-12 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlecomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
