# Generated by Django 4.2.4 on 2023-08-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_alter_articleview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replay', to='article_module.articlecomments'),
        ),
    ]
