# Generated by Django 4.2.4 on 2023-08-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_remove_article_users_remove_articlecomments_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='is_view_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
