# Generated by Django 4.2.4 on 2023-08-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد فعال سازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_special_user',
            field=models.BooleanField(blank=True, null=True, verbose_name='کاربر ویژه / عادی'),
        ),
    ]
