# Generated by Django 4.2.4 on 2023-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_special_user',
            field=models.BooleanField(default=False, verbose_name='کاربر ویژه / عادی'),
            preserve_default=False,
        ),
    ]
